exports.VIEW_SAVE = 'VIEW_SAVE';
exports.CONFIG_SAVE = 'CONFIG_SAVE';
exports.THEME_CHANGE = 'THEME_CHANGE';
exports.RECEIVE_VIEWS = 'RECEIVE_VIEWS';
exports.RECEIVE_TYPE = 'RECEIVE_TYPE';
exports.RECEIVE_SERVERS = 'RECEIVE_SERVERS';
exports.VALIDATION_ERROR = 'VALIDATION_ERROR';
exports.FETCH_FAILED = 'FETCH_FAILED';